function(plugins_realtime_sanitizer target)
    target_compile_definitions(${target} PUBLIC PLUGINS_WITH_RTSAN)
    target_compile_options(${target} PUBLIC -fsanitize=realtime)
    target_link_options(${target} PUBLIC -fsanitize=realtime)
endfunction()

function(plugins_address_sanitizer target)
    target_compile_definitions(${target} PUBLIC PLUGINS_WITH_ASAN)
    target_compile_options(${target} PUBLIC -fsanitize=address)
    target_link_options(${target} PUBLIC -fsanitize=address)
endfunction()

function(plugins_undefined_sanitizer target)
    target_compile_definitions(${target} PUBLIC PLUGINS_WITH_USAN)
    target_compile_options(${target} PUBLIC -fsanitize=undefined)
    target_link_options(${target} PUBLIC -fsanitize=undefined)
endfunction()

function(plugins_thread_sanitizer target)
    target_compile_definitions(${target} PUBLIC PLUGINS_WITH_TSAN)
    target_compile_options(${target} PUBLIC -fsanitize=thread)
    target_link_options(${target} PUBLIC -fsanitize=thread)
endfunction()

function(plugins_memory_sanitizer target)
    target_compile_definitions(${target} PUBLIC PLUGINS_WITH_MSAN)
    target_compile_options(${target} PUBLIC -fsanitize=memory)
    target_link_options(${target} PUBLIC -fsanitize=memory)
endfunction()

function(plugins_leak_sanitizer target)
    target_compile_definitions(${target} PUBLIC PLUGINS_WITH_LSAN)
    target_compile_options(${target} PUBLIC -fsanitize=leak)
    target_link_options(${target} PUBLIC -fsanitize=leak)
endfunction()
