name: SeamLess Plugin Suite

on:
  workflow_dispatch: # lets you run a build from github.com
  # Runs the workflow on push events but only for the develop branch
  push:
    branches: [ main ]

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: seamless-plugin-suite
  PLUGINS: SeamLess_Client SeamLess_Main
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  # Use up to 4 cpus to build juceaide, etc
  CMAKE_BUILD_PARALLEL_LEVEL: 4 
  # Name of the build directory
  BUILD_DIR: build

jobs:

  setup:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macOS-latest
            name: macOS
            ccache: ccache
          - os: windows-latest
            name: Windows
            ccache: sccache
    runs-on: ${{ matrix.os }}
    steps:

      #A simple printout of the matrix
      - name: printout
        shell: bash
        run: |
          for PLUGIN in $PLUGINS; do 
            echo "PLUGIN=$PLUGIN";
            echo "matrix.name=${{ matrix.name }}";
            echo "matrix.os=${{ matrix.os }}";
            echo "matrix.ccache=${{ matrix.ccache }}";
          done;
      
      # Setting up the environment variables for the paths so we can use them later
      - name: setup environment variables
        shell: bash
        run: |
          for PLUGIN in $PLUGINS; do
            echo "$PLUGIN_ARTEFACTS_PATH=${{ env.BUILD_DIR }}/$PLUGIN/$PLUGIN_artefacts/${{ env.BUILD_TYPE }}" >> $GITHUB_ENV
            echo "$PLUGIN_VST3_PATH=${{ env.BUILD_DIR }}/$PLUGIN/$PLUGIN_artefacts/${{ env.BUILD_TYPE }}/VST3/$PLUGIN.vst3" >> $GITHUB_ENV
          done
          if [ "${{ matrix.name }}" == "macOS" ]; then
            echo "macOS test"
          elif [ "${{ matrix.name }}" == "Windows" ]; then
            echo "Windows test"
          else
            echo "Unknown OS"
          fi