name: SeamLess Suite

on:
  workflow_dispatch: # lets you run a build from github.com
  # Runs the workflow on push events but only for the develop branch
  push:
    branches: [ main ]

jobs:

  setup:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        plugin: [client, main]
        include:
          - os: macOS-latest
            name: macOS
            ccache: ccache
          - os: windows-latest
            name: Windows
            ccache: sccache
    runs-on: ${{ matrix.os }}
    steps:
      - name: printout
        run: |
          echo "matrix.name=${{ matrix.name }}"
          echo "matrix.os=${{ matrix.os }}"
          echo "matrix.ccache=${{ matrix.ccache }}"
          echo "matrix.plugin=${{ matrix.plugin }}"