name: SeamLess Suite

on:
  workflow_dispatch: # lets you run a build from github.com
  # Runs the workflow on push events but only for the develop branch
  push:
    branches: [ main ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - id: matrix
        run: |
          echo "{value}={"a"}" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - run: |
          echo "${{ matrix.value }}"